package databasegen

import (
	"bufio"
	"fmt"
	"log"
	"os"
	"path"

	"github.com/abramov-ks/mk4speedcams/pkg/speedcamonline"
	"github.com/abramov-ks/mk4speedcams/pkg/tpd"
)

type Config struct {
	OutputDir string `yaml:"output_dir"`
	// Deprecated: headers are generated by pkg/tpd now, kept so old configs still load.
	IdxHeaderFile string `yaml:"idx_header_file"`
	UrlHeaderFile string `yaml:"url_header_file"`
}

func (config *Config) getOutputDirPath() string {
	execPath, _ := os.Executable()
	return path.Join(execPath, "../../"+config.OutputDir)
}

type Result struct {
	IdxFile      string
	UrlFile      string
	PoisonFile   string
	RecordsCount int
}

// GenerateFromDatabase writes poison.txt (for poipatch / POISoN Patcher) and the
// TPD speedcam tables 0009.IDX / 0010.URL.
func (config Config) GenerateFromDatabase(database []speedcamonline.SpeedcamRecord) (*Result, error) {
	var result = Result{}

	log.Println("Start DB generating")

	dir := config.getOutputDirPath()
	result.IdxFile = dir + "/0009.IDX"
	result.UrlFile = dir + "/0010.URL"
	result.PoisonFile = dir + "/poison.txt"

	poisonFile, err := os.Create(result.PoisonFile)
	if err != nil {
		return nil, err
	}
	w := bufio.NewWriter(poisonFile)

	pois := make([]tpd.POI, 0, len(database))
	for _, line := range database {
		fmt.Fprintf(w, "%f,%f\n", line.Long, line.Lat)
		pois = append(pois, tpd.POI{Lon: line.Long, Lat: line.Lat, Name: "SpeedCam"})
		result.RecordsCount++
	}
	if err := w.Flush(); err != nil {
		return nil, err
	}
	poisonFile.Close()

	table := tpd.Table{Category: "0013", FormPath: "ENG/SE/SF_0013.HTM", NameLen: 8}
	if err := table.Write(pois, result.IdxFile, result.UrlFile); err != nil {
		return nil, err
	}

	return &result, nil
}
